language: c
sudo: false
notifications:
  irc: "irc.freenode.net#haskell-india"

matrix:
  include:
    - env: GHCVER=7.10.3 CABALVER=1.22. STACKVER=lts-6.14
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3], sources: [hvr-ghc]}}
      
before-install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - wget "https://www.stackage.org/$STACKVER/cabal.config";

install:
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config  # Bug #9221
  - cabal install --only-dependencies

script:
  - cabal build  # build the site.hs
  - ./dist/build/site/site build
  
branches:
  only:
    - develop